/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.dictionary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class DictionaryTest {
   

}
