/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.dictionary;

public class App {
   

    public static void main(String[] args) {
        Dictionary dictionary = new Dictionary();

        dictionary.addWordsToDictionary("apple", "apfel");
        dictionary.addWordsToDictionary("banana", "banane");
        dictionary.addWordsToDictionary("orange", "orange");
        dictionary.addWordsToDictionary("grape", "traube");
        dictionary.addWordsToDictionary("strawberry", "erdbeere");
        dictionary.addWordsToDictionary("carrot", "karotte");
        dictionary.addWordsToDictionary("tomato", "tomate");
        dictionary.addWordsToDictionary("potato", "kartoffel");
        dictionary.addWordsToDictionary("cucumber", "gurke");
        dictionary.addWordsToDictionary("lettuce", "salat");

        System.out.println(dictionary.getEnglischWord("apfel"));

        System.out.println(dictionary.getGermanWord("lettuce"));
        
        System.out.println("removed: " +dictionary.removeWordFromDictionary("orange"));
        System.out.println(dictionary.removeWordFromDictionary("orange"));

        System.out.println("Changed: " +dictionary.changeTranslation("apple", "grüner apfel")
         +", into: " + dictionary.getGermanWord("apple"));

        System.out.println(dictionary.findWordsByLetter("c").toString());
    }
}
